name: Python (Release)

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: "Release type - major, minor or patch"
        required: true
        default: "minor"
        type: choice
        options:
          - "major"
          - "minor"
          - "patch"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Python build utilities
        run: pip install -r requirements.txt
      - name: Build
        run: flit build --no-use-vcs
      - name: upgrade & push version
        id: upgrade
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          bump-my-version bump ${{ github.event.inputs.releaseType }}
          new_version=$(bump-my-version show current_version)
          tag_name="v$new_version"
          git push
          git push origin "$tag_name"
          echo "tag_name=$tag_name" >> "$GITHUB_OUTPUT"

      - name: Github Release
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          tag_name: ${{ steps.upgrade.outputs.tag_name }}
          files: dist/*
          generate_release_notes: true
